DROP TABLE IF EXISTS `merch`;
		
CREATE TABLE `merch` (
  `id` INTEGER PRIMARY KEY NULL DEFAULT NULL,
  `name` VARCHAR(150) NULL DEFAULT NULL,
  `stars` DECIMAL(5) NULL DEFAULT NULL,
  `reviews` INTEGER(6) NULL DEFAULT NULL,
  `price` VARCHAR(25) NULL DEFAULT NULL,
  `imageUrl` VARCHAR(255) NULL DEFAULT NULL,
  `prime` INTEGER(1) NULL DEFAULT NULL
);